<source media="(prefers-color-scheme: dark)" srcset="[https://raw.githubusercontent.com/codehashira23/codehashira23/output/github-contribution-grid-snake-dark.svg">](https://raw.githubusercontent.com/codehashira23/codehashira23/output/github-contribution-grid-snake-dark.svg">)
<source media="(prefers-color-scheme: light)" srcset="[https://raw.githubusercontent.com/codehashira23/codehashira23/output/github-contribution-grid-snake.svg">](https://raw.githubusercontent.com/codehashira23/codehashira23/output/github-contribution-grid-snake.svg">)
<img alt="github contribution grid snake animation" src="[https://raw.githubusercontent.com/codehashira23/codehashira23/output/github-contribution-grid-snake.svg">](https://raw.githubusercontent.com/codehashira23/codehashira23/output/github-contribution-grid-snake.svg">)name: Generate Snake Animation

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC daily
  # Allow manual triggering of the workflow
  workflow_dispatch: # Allows manual triggering
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main # or your default branch name

permissions:
  contents: write # This is important for the action to push to the repository

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # Step 2: Generate the snake animations
      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-generator
        with:
          # GitHub username to generate the animation for
          github_user_name: ${{ github.repository_owner }}
          # These output paths need to match what's referenced in your README
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Step 3: Deploy the generated files to the 'output' branch
      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output # The branch where the generated files will be stored
          force_orphan: true # Use this to ensure the branch only contains the latest files
          commit_message: "Generate Snake Animation"
